// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx94b5rIzU-41eW4Dv_Z6SDIponfX1ZNo',
    appId: '1:187587171163:web:60a5b6a6cc4d4ffdc4c07e',
    messagingSenderId: '187587171163',
    projectId: 'horizon-dbba0',
    authDomain: 'horizon-dbba0.firebaseapp.com',
    storageBucket: 'horizon-dbba0.firebasestorage.app',
    measurementId: 'G-G1W3RQ58C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABskrNPPpkz74DYKFPMkohKyyrPrk-x80',
    appId: '1:187587171163:android:331d6a3f3c93c7d4c4c07e',
    messagingSenderId: '187587171163',
    projectId: 'horizon-dbba0',
    storageBucket: 'horizon-dbba0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAakZ84EMeN43rBFAA4A2WgWRSfWUaxRRg',
    appId: '1:187587171163:ios:95fd1d3e20cfd307c4c07e',
    messagingSenderId: '187587171163',
    projectId: 'horizon-dbba0',
    storageBucket: 'horizon-dbba0.firebasestorage.app',
    iosBundleId: 'com.vibecodingmind.horizon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAakZ84EMeN43rBFAA4A2WgWRSfWUaxRRg',
    appId: '1:187587171163:ios:95fd1d3e20cfd307c4c07e',
    messagingSenderId: '187587171163',
    projectId: 'horizon-dbba0',
    storageBucket: 'horizon-dbba0.firebasestorage.app',
    iosBundleId: 'com.vibecodingmind.horizon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx94b5rIzU-41eW4Dv_Z6SDIponfX1ZNo',
    appId: '1:187587171163:web:a05a014b7556d039c4c07e',
    messagingSenderId: '187587171163',
    projectId: 'horizon-dbba0',
    authDomain: 'horizon-dbba0.firebaseapp.com',
    storageBucket: 'horizon-dbba0.firebasestorage.app',
    measurementId: 'G-1V3FE65LCY',
  );
}
